// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8bp3LeEJFLGAzi__JdoS2iZeDugyoJ78',
    appId: '1:724578803039:web:0dd4bc9c8ad61336046aea',
    messagingSenderId: '724578803039',
    projectId: 'bateponto-f5f02',
    authDomain: 'bateponto-f5f02.firebaseapp.com',
    storageBucket: 'bateponto-f5f02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFh2Cxq5spjWh5sPvRL6E6OkSAXlh7X8U',
    appId: '1:724578803039:android:31dd237b280a87fe046aea',
    messagingSenderId: '724578803039',
    projectId: 'bateponto-f5f02',
    storageBucket: 'bateponto-f5f02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoEK_PdYBOJaRLVBJq2-tPE68FvSKDSJY',
    appId: '1:724578803039:ios:bc56beafb8d7f302046aea',
    messagingSenderId: '724578803039',
    projectId: 'bateponto-f5f02',
    storageBucket: 'bateponto-f5f02.firebasestorage.app',
    iosBundleId: 'com.example.batepontoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoEK_PdYBOJaRLVBJq2-tPE68FvSKDSJY',
    appId: '1:724578803039:ios:bc56beafb8d7f302046aea',
    messagingSenderId: '724578803039',
    projectId: 'bateponto-f5f02',
    storageBucket: 'bateponto-f5f02.firebasestorage.app',
    iosBundleId: 'com.example.batepontoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8bp3LeEJFLGAzi__JdoS2iZeDugyoJ78',
    appId: '1:724578803039:web:f6c0b08729c74d5d046aea',
    messagingSenderId: '724578803039',
    projectId: 'bateponto-f5f02',
    authDomain: 'bateponto-f5f02.firebaseapp.com',
    storageBucket: 'bateponto-f5f02.firebasestorage.app',
  );
}
